.TH jikes 1 "10 January 2000" 
.SH NAME
jikes \- java source to bytecode compiler
.SH SYNOPSIS
\fBjikes\fP
[\fB\-classpath\fP path]
[\fB\-d\fP directory]
[\fB\-debug\fP]
[\fB\-depend\fP]
[\fB\-deprecation\fP]
[\fB\-g\fP]
[\fB\-nowarn\fP]
[\fB\-nowrite\fP]
[\fB\-O\fP]
[\fB\-verbose\fP]
[\fB\-Xdepend\fP]
[\fB\-Xstdout\fP]
[\fB\+\+\fP]
[\fB\+B\fP]
[\fB\+CSO\fP]
[\fB\+D\fP]
[\fB\+DR=\fP filename]
[\fB\+E\fP]
[\fB\+F\fP]
[\fB\+K\fP]
[\fB\+M\fP]
[\fB\+P\fP]
[\fB\+T\fPnn]
[\fB\+U\fP]
[\fB\+Z\fP]
file.java
\&.\|.\|.
.SH DESCRIPTION
\fBJikes\fP translates Java(TM) source files to bytecode. Features
include strict adherence to the language specification, automatic
makefile generation and incremental compilation. It is maintained
by the Jikes Project, \fIhttp://ibm.com/developerworks/opensource\fP.

.SH OPTIONS
\fBJikes\fP may be invoked with the following command-line options:
.TP
\fB\-classpath\fP path
use path for CLASSPATH
.TP
\fB\-d\fP directory
write class files in specified directory
.TP
\fB\-debug
no effect (recognized for compatibility)
.TP
\fB\-depend
recompile all used classes
.TP
\fB\-deprecation
report uses of deprecated features
.TP
\fB\-g
debug (generate LocalVariableTable attribute)
.TP
\fB\-nowarn
do not issue warning messages
.TP
\fB\-nowrite
do not write any class files
.TP
\fB\-O
do not write LineNumberTable
.TP
\fB\-verbose
list files read and written
.TP
\fB\-Xdepend
same as -depend
.TP
\fB\-Xstdout
write error messages to standard output, not stderr
.TP
\fB\+\+
compile in incremental mode
.TP
\fB\+B
do not invoke bytecode generator
.TP
\fB\+CSO
Select to use same classpath search order as javac. 
.TP
\fB\+D
report errors immediately in emacs-form without buffering
.TP
\fB\+DR\fP\=filename
write report of dependencies to specified file
.TP
\fB\+E
list errors in emacs-form
.TP
\fB\+F
do full dependence check except for Zip and Jar files
.TP
\fB\+K\fPname\=TypeKeyWord
map name to type keyword
.TP
\fB\+M
generate makefile dependencies
.TP
\fB\+P
Pedantic compilation - issues lots of warnings
.TP
\fB\+T\fPnn
set value of tab to nn spaces
.TP
\fB\+U
do full dependence check including Zip and Jar files
.TP
\fB\+Z
treat cautions as errors
.PP
An argument may have the form \fI@file\fP; each line of \fIfile\fP is
then interpreted as an argument, except that lines beginning with
\fI@\fP are not expanded recursively. 

.SH FILES
\fBJikes\fP requires a colon-separated list of directories or files
that tell it where to look for any needed class or source files, for
example ".:$HOME/java/lib/classes.zip".  A definition given with the
environment variable \fIJIKESPATH\fP takes precedence over one given
with \fICLASSPATH\fP; a definition using the \fI-classpath\fP option
takes precedence over any value specified via the environment. 
.SH "SEE ALSO"
.TP
\fIhttp://ibm.com/developerworks/opensource\fP
See the Jikes Project section 
for news of recent developments,
to download new versions, 
to report bugs, or 
to learn how to participate in the development process.
.TP
\fIjikes.htm\fP
for a more complete description in FAQ format. This file is
distributed with the program as part of its documentation, and is
also available from the Jikes Project URL.

.SH COPYRIGHT
Copyright \(co 1996, 2000,
International Business Machines Corporation and others. All Rights Reserved.
.PP
\fBJikes\fP is licensed under the \fIIBM Public License\fP, included
in the file \fIlicense.htm\fP distributed with the program, and also
available at the Jikes Project URL.

.SH NOTES
Java is a registered trademark of Sun Microsystems, Inc.



