.TH jikes 1
.SH NAME
jikes \- java source to bytecode compiler
.SH SYNOPSIS
\fBjikes\fP
[\fB\-bootclasspath\fP path]
[\fB\-classpath\fP path]
[\fB\-d\fP directory]
[\fB\-debug\fP]
[\fB\-depend\fP]
[\fB\-deprecation\fP]
[\fB\-encoding\fP encoding]
[\fB\-extdirs\fP path]
[\fB\-g\fP]
[\fB\-nowarn\fP]
[\fB\-nowrite\fP]
[\fB\-O\fP]
[\fB\-verbose\fP]
[\fB\-sourcepath\fP path]
[\fB\-Xdepend\fP]
[\fB\-Xstdout\fP]
[\fB\+\+\fP]
[\fB\+B\fP]
[\fB\+OLDCSO\fP]
[\fB\+D\fP]
[\fB\+DR=\fPfilename]
[\fB\+E\fP]
[\fB\+F\fP]
[\fB\+K\fP]
[\fB\+M\fP]
[\fB\+P\fP]
[\fB\+T\fPnn]
[\fB\+U\fP]
[\fB\+Z\fP]
[\fB\+c\fP]
file.java
\&.\|.\|.
.SH DESCRIPTION
\fBJikes\fP translates Java(TM) source files to bytecode. Features
include strict adherence to the language specification, automatic
makefile generation and incremental compilation. It is maintained
by the Jikes Project.

.SH OPTIONS
\fBJikes\fP may be invoked with the following command-line options:
.TP
\fB\-bootclasspath\fP path
use path for the bootclasspath
.TP
\fB\-classpath\fP path
use path for CLASSPATH
.TP
\fB\-d\fP directory
write class files in specified directory
.TP
\fB\-debug
no effect (recognized for compatibility)
.TP
\fB\-depend
recompile all used classes
.TP
\fB\-deprecation
report uses of deprecated features
.TP
\fB\-encoding
use specified encoding to read source files
.TP
\fB\-extdirs\fP path
use path for extensions directories
.TP
\fB\-g
debug (generate LocalVariableTable attribute)
.TP
\fB\-nowarn
do not issue warning messages
.TP
\fB\-nowrite
do not write any class files
.TP
\fB\-O
do not write LineNumberTable
.TP
\fB\-sourcepath\fP path
use path for specifying "source only" directories
.TP
\fB\-verbose
list files read and written
.TP
\fB\-Xdepend
same as -depend
.TP
\fB\-Xstdout
write error messages to standard output, not stderr
.TP
\fB\+\+
compile in incremental mode
.TP
\fB\+B
do not invoke bytecode generator
.TP
\fB\+OLDCSO
Select to use same classpath search order as in older versions of Jikes (for compatibility). 
.TP
\fB\+D
report errors immediately in emacs-form without buffering
.TP
\fB\+DR\fP\=filename
write report of dependencies to specified file
.TP
\fB\+E
list errors in emacs-form
.TP
\fB\+F
do full dependence check except for Zip and Jar files
.TP
\fB\+K\fPname\=TypeKeyWord
map name to type keyword
.TP
\fB\+M
generate makefile dependencies
.TP
\fB\+P
Pedantic compilation - issues lots of warnings
.TP
\fB\+T\fPnn
set value of tab to nn spaces
.TP
\fB\+U
do full dependence check including Zip and Jar files
.TP
\fB\+Z
treat cautions as errors
.TP
\fB\+c
do not discard comments from lexer output
.PP
An argument may have the form \fI@file\fP; each line of \fIfile\fP is
then interpreted as an argument, except that lines beginning with
\fI@\fP are not expanded recursively.

.SH FILES
\fBJikes\fP has several options related to classpath searching.
The -bootclasspath, -extdirs, and -sourcepath options are the same
as in javac.  In addition to being specified on the command line, the
environment variables BOOTCLASSPATH, EXTDIRS, and SOURCEPATH may also be
used to specify values for these options, respectively.  \fBJikes\fP also
has the -classpath option as in javac, with the corresponding environment
variable CLASSPATH.  The classpath may also be specified in the environment
variable JIKESPATH.  If JIKESPATH and CLASSPATH coexist, preference will be
given to JIKESPATH.  A value specified on the command line will be always
be given preference over the value of any environment variable.  All the
directories and files specified in these options or environment variables
must be in a colon-separated list, e.g., ".:$HOME/java/jre/lib/rt.jar".
.SH "SEE ALSO"
.TP
Jikes Project homepage 
\fIhttp://ibm.com/developerworks/opensource/jikes/\fP
for news of recent developments,
to download new versions, 
to report bugs, or 
to learn how to participate in the development process.

.SH COPYRIGHT
Copyright \(co 1996, 1997, 1998, 1999, 2000, 2001,
International Business Machines Corporation and others. All Rights Reserved.
.PP
\fBJikes\fP is licensed under the \fIIBM Public License\fP, included
in the file \fIlicense.htm\fP distributed with the program, and also
available at the Jikes Project URL.
.pp
Portions of \fBJikes\fP are derived from prior, freely distributable
projects.  For more details on this code, see the comments in
src/double.h, src/platform.h, and src/unzip.h.

.SH NOTES
Java is a registered trademark of Sun Microsystems, Inc.
