.TH jikes 1
.SH NAME
jikes \- java source to bytecode compiler
.SH SYNOPSIS
jikes [\fI\-options\fP] [\fI\+options\fP] [\fI\@files\fP]
      \fIfile.java\fP\&.\|.\|.

Options, @files, and filenames may be intermixed. Individual options
should not be repeated, unless noted below.

.SH DESCRIPTION
\fBJikes\fP translates Java(TM) source files to bytecode. Features
include strict adherence to the language specification, automatic
makefile generation and incremental compilation. It is maintained
by the Jikes Project.

At this time, jikes only recognizes the full name of options; you
cannot abbreviate or group them. You can give different argument types
in any order. Options are global, so they affect compilation of files
listed earlier on the command line. Duplicated options override the
previous one, unless otherwise listed. If an option is listed in the
form \fB\+T\=n\fP, it can also be specified as \fB\+T n\fP or even
\fB\+Tn\fP.

.SH OPTIONS
\fBJikes\fP may be invoked with the following command-line options:

.TP
\fB\-bootclasspath\fP \fIpath\fP
.TP
\fB\-\-bootclasspath\fP \fIpath\fP
Use path for the bootclasspath. This path is searched first for
library class files, and is usually set to \fBjava/lib/classes.zip\fP
or \fBjava/jre/lib/rt.jar\fP.

.TP
\fB\-classpath\fP \fIpath\fP
.TP
\fB\-cp\fP \fIpath\fP
.TP
\fB\-\-classpath\fP \fIpath\fP
Use path for CLASSPATH. This path is searched for both user source and
compiled class files.
.\" Someone should better document the search algorithm used.

.TP
\fB\-d\fP \fIdirectory\fP
.TP
\fB\-\-target\-directory\fP \fIdirectory\fP
Write class files in the specified directory. Note that this directory is
NOT in your classpath unless you list it there as well.

.TP
\fB\-debug
No effect (recognized for compatibility).

.TP
\fB\-depend
.TP
\fB\-\-depend
.TP
\fB\-Xdepend
Recompile all used classes.

.TP
\fB\-deprecation
.TP
\fB\-\-deprecation
Report uses of deprecated features.

.TP
\fB\-encoding\fP \fIencoding\fP
.TP
\fB\-\-encoding\fP \fIencoding\fP
Use specified encoding to read source files. This is not available in
some builds, because it requires a working iconv or ICU encoder.
\fBNote:\fP in particular that the Windows binary provided for
download does NOT include support for the encoding option as there
is not a transcoding library on windows by default. You can tell if
a binary has encoding support or not, but running \fIjikes \-\-help\fP
and looking for the \-\-encoding option: if it is not listed, then
this binary does NOT include support for encoding.

.TP
\fB\-extdirs\fP \fIpath\fP
.TP
\fB\-\-extdirs\fP \fIpath\fP
Use path for extensions directories. This is typically set to grab jar
and zip extension files located in \fBjava/jre/lib/ext\fP.

.TP
\fB\-g
Equivalent to \fB\-g\:source\|,lines\|,vars\fP.

.TP
\fB\-g\:none\fP\||\|{\fBsource\|,lines\|,vars\fP\|}
Specify which of three classfile debug options should be enabled. If
this is not specified, the default is
\fBsource\|,lines\fP. \fBsource\fP stores the filename of the source
file in the class file, \fBlines\fP adds line number tracking to tie
bytecodes to their location in the source file, and \fBvars\fP adds a
table in the class file which stores the name of local variables and
parameters, as well as their scope.

.TP
\fB\-help
.TP
\fB\-\-help
.TP
\fB\-h
.TP
\fB\-\|?
Prints a helpful summary of options, then exit. Overrides all other
options, and nothing is compiled.

.TP
\fB\-J\fP\&.\|.\|.
No effect, since jikes is native code, and does not need a Virtual
Machine (ignored for compatibility).

.TP
\fB\-nowarn
.TP
\fB\-\-nowarn
.TP
\fB\-q
Do not issue warning messages.

.TP
\fB\-nowrite
.TP
\fB\-\-nowrite
Do not write any class files, but list which ones would be written if
used with \fB\-verbose\fP.

.TP
\fB\-O
.TP
\fB\-\-optimize
Optimize the bytecode. Technically, this means jikes should inline
private and final methods where appropriate, but currently it does
nothing.

.TP
\fB\-source\fP \fIrelease\fP
.TP
\fB\-\-source\fP \fIrelease\fP
Specify which Java SDK release the source syntax obeys. For example,
to compile code with the \fIassert\fP keyword, you would specify
\fB\-source 1.4\fP. Recognized releases are \fB1.1\fP through
\fB1.4\fP. If unspecified, this defaults to \fB1.3\fP.

.TP
\fB\-sourcepath\fP path
.TP
\fB\-\-sourcepath\fP path
Use path for specifying user "source only" directories. Class files in
this path are ignored unless listed in other paths.

.TP
\fB\-target\fP \fIrelease\fP
.TP
\fB\-\-target\fP \fIrelease\fP
Specify which Java SDK release the bytecode should target. For
example, in Java 1.4, exception chaining was introduced, so a failed
class literal can chain the NoClassDefFoundError to its original
ClassNotFoundException, rather than the old behavior in Java 1.3 where
the original exception is just discarded. You would get the new
behavior by specifying \fB\-target 1.4\fP. Recognized releases are
\fB1.1\fP through \fB1.4\fP. If unspecified, this defaults to whatever
\fB\-source\fP level is in force.

.TP
\fB\-verbose
.TP
\fB\-\-verbose
.TP
\fB\-v
List files read and written. Also useful with \fB\-nowrite\fP for a
dry run to track dependencies.

.TP
\fB\-version
.TP
\fB\-\-version
.TP
\fB\-V
Print a version message, and contact information, then exit. Overrides
all other options except \fB\-\-help\fP, and nothing is compiled.

.TP
\fB\-Xstdout
Write error messages to standard output, not stderr. At the moment,
this is incompatible with javac, which takes an argument as the name
of the file where it will direct compiler message output.

.\" We ought to give the enhanced versions long names...

.TP
\fB\+\+
Compile in incremental mode.

.TP
\fB\+B
Do not invoke bytecode generator.

.TP
\fB\+D
Report errors immediately in emacs-form without buffering.

.TP
\fB\+DR\=\fIfilename\fP
Write report of dependencies to specified file.
.\" We ought to change this to be a one-letter name...

.TP
\fB\+E
List errors in emacs-form.

.TP
\fB\+F
Do full dependence check except for Zip and Jar files.

.TP
\fB\+K\fIname\fB\=\fITypeKeyWord\fP
Map name to type keyword. Multiple options are needed to change more
than one type keyword.

.TP
\fB\+M
Generate makefile dependencies.

.TP
\fB\+OLDCSO
Select to use same classpath search order as in older versions of
Jikes (for compatibility).
.\" Someone should document how this differs from regular search order.

.TP
\fB\+P\fP[\fIflags\fP]
Pedantic compilation - issues lots of warnings. This option may be
listed multiple times, with cumulative effect. With no flags, this
turns on the default set of pedantic warnings. Specifying a flag will
then turn on or off a particular warning, depending on the presence of
the \fIno-\fP prefix. At present, the recognized flags are
\fBmodifier-order\fP, which warns about the recommended ordering of
multiple modifiers; and \fBredundant-modifiers\fP, which warns about
explicitly mentioning an implied modifier.  Both are turned on by
default in pedantic compilation mode. Multiple \fB\+P\fP options are
cumulative in effect. For example, to get all pedantic warnings except
modifier ordering, use \fB\+P \+Pno-modifier-order\fP. To get just
warnings about redundant modifiers, without other pedantic warnings,
use \fB\+Predundant-modifiers\fP.

.TP
\fB\+T\f\=In\fP
Set value of tab to \fIn\fP spaces. If not specified, the default is 8.

.TP
\fB\+U
Do full dependence check including Zip and Jar files.

.TP
\fB\+Z
Treat cautions as errors. Unfortunately, at the moment, this will not
promote warnings, just cautions.

.PP
An argument may have the form \fI@file\fP, which names a \fIfile\fP
holding additional command-line arguments.  Each line in that file is
treated as an argument, except that lines beginning with \fI@\fP are
not expanded recursively.  Lines may optionally be quoted using either
single or double quotes.  There are no escape characters (\fI'\\'\fP
is not treated as special).

.SH FILES
\fBJikes\fP has several options related to classpath searching.
The -bootclasspath, -extdirs, and -sourcepath options are the same
as in javac.  In addition to being specified on the command line, the
environment variables \fBBOOTCLASSPATH\fP, \fBEXTDIRS\fP, and
\fBSOURCEPATH\fP may also be used to specify values for these options,
respectively.  \fBJikes\fP also has the -classpath option as in javac,
with the corresponding environment variable \fBCLASSPATH\fP.  The
classpath may also be specified in the environment variable
\fBJIKESPATH\fP, although this use is discouraged.  If \fBJIKESPATH\fP
and \fBCLASSPATH\fP coexist, preference will be given to
\fBJIKESPATH\fP.  A value specified on the command line will be always
be given preference over the value of any environment variable.  All
the directories and files specified in these options or environment
variables must be in a colon-separated list, e.g.,
".:$HOME/java/jre/lib/rt.jar".

.SH "SEE ALSO"
Jikes Project homepage 
\fIhttp://ibm.com/developerworks/opensource/jikes/\fP
for news of recent developments, to download new versions, to report
bugs, or to learn how to participate in the development process.

.SH COPYRIGHT
Copyright \(co 1996, 1997, 1998, 1999, 2000, 2001, 2002
International Business Machines Corporation and others. All Rights Reserved.

.PP
\fBJikes\fP is licensed under the \fIIBM Public License\fP, included
in the file \fIlicense.htm\fP distributed with the program, and also
available at the Jikes Project URL.
.pp
Portions of \fBJikes\fP are derived from prior, freely distributable
projects.  For more details on this code, see the comments in
src/double.h, src/platform.h, and src/unzip.h.

.SH NOTES
Java is a registered trademark of Sun Microsystems, Inc.
