// DO NOT MODIFY THIS FILE - it is generated using jikespg on java.g.

#ifndef javasym_INCLUDED
#define javasym_INCLUDED

#ifdef HAVE_JIKES_NAMESPACE
namespace Jikes { // Open namespace Jikes block
#endif

enum {
      TK_abstract = 22,
      TK_assert = 74,
      TK_boolean = 4,
      TK_break = 75,
      TK_byte = 5,
      TK_case = 101,
      TK_catch = 102,
      TK_char = 6,
      TK_class = 51,
      TK_continue = 76,
      TK_default = 99,
      TK_do = 77,
      TK_double = 7,
      TK_else = 100,
      TK_extends = 78,
      TK_false = 39,
      TK_final = 23,
      TK_finally = 103,
      TK_float = 8,
      TK_for = 79,
      TK_if = 80,
      TK_implements = 106,
      TK_import = 97,
      TK_instanceof = 59,
      TK_int = 9,
      TK_interface = 56,
      TK_long = 10,
      TK_native = 24,
      TK_new = 20,
      TK_null = 40,
      TK_package = 104,
      TK_private = 25,
      TK_protected = 26,
      TK_public = 27,
      TK_return = 81,
      TK_short = 11,
      TK_static = 21,
      TK_strictfp = 28,
      TK_super = 13,
      TK_switch = 82,
      TK_synchronized = 16,
      TK_this = 29,
      TK_throw = 83,
      TK_throws = 107,
      TK_transient = 30,
      TK_true = 41,
      TK_try = 84,
      TK_void = 31,
      TK_volatile = 32,
      TK_while = 67,
      TK_Identifier = 1,
      TK_IntegerLiteral = 42,
      TK_LongLiteral = 43,
      TK_FloatLiteral = 44,
      TK_DoubleLiteral = 45,
      TK_CharacterLiteral = 46,
      TK_StringLiteral = 47,
      TK_PLUS_PLUS = 17,
      TK_MINUS_MINUS = 18,
      TK_EQUAL_EQUAL = 68,
      TK_LESS_EQUAL = 60,
      TK_GREATER_EQUAL = 61,
      TK_NOT_EQUAL = 69,
      TK_LEFT_SHIFT = 52,
      TK_RIGHT_SHIFT = 48,
      TK_UNSIGNED_RIGHT_SHIFT = 50,
      TK_PLUS_EQUAL = 85,
      TK_MINUS_EQUAL = 86,
      TK_MULTIPLY_EQUAL = 87,
      TK_DIVIDE_EQUAL = 88,
      TK_AND_EQUAL = 89,
      TK_OR_EQUAL = 90,
      TK_XOR_EQUAL = 91,
      TK_REMAINDER_EQUAL = 92,
      TK_LEFT_SHIFT_EQUAL = 93,
      TK_RIGHT_SHIFT_EQUAL = 94,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 95,
      TK_OR_OR = 98,
      TK_AND_AND = 70,
      TK_PLUS = 33,
      TK_MINUS = 34,
      TK_NOT = 53,
      TK_REMAINDER = 62,
      TK_XOR = 71,
      TK_AND = 65,
      TK_MULTIPLY = 57,
      TK_OR = 72,
      TK_TWIDDLE = 54,
      TK_DIVIDE = 63,
      TK_GREATER = 35,
      TK_LESS = 36,
      TK_LPAREN = 2,
      TK_RPAREN = 12,
      TK_LBRACE = 38,
      TK_RBRACE = 49,
      TK_LBRACKET = 14,
      TK_RBRACKET = 73,
      TK_SEMICOLON = 3,
      TK_QUESTION = 66,
      TK_COLON = 58,
      TK_COMMA = 37,
      TK_DOT = 19,
      TK_EQUAL = 64,
      TK_BodyMarker = 108,
      TK_enum = 55,
      TK_AT = 15,
      TK_ELLIPSIS = 105,
      TK_const = 109,
      TK_goto = 110,
      TK_ERROR = 111,
      TK_EOF = 96
     };

#ifdef HAVE_JIKES_NAMESPACE
} // Close namespace Jikes block
#endif

#endif /* javasym_INCLUDED */
