// $Id: javasym.h,v 1.29 2004/01/23 12:07:03 ericb Exp $
// DO NOT MODIFY THIS FILE - it is generated using jikespg on java.g.
//
// This software is subject to the terms of the IBM Jikes Compiler Open
// Source License Agreement available at the following URL:
// http://ibm.com/developerworks/opensource/jikes.
// Copyright (C) 1996, 2003 IBM Corporation and others.  All Rights Reserved.
// You must accept the terms of that agreement to use this software.
//

#ifndef javasym_INCLUDED
#define javasym_INCLUDED

#ifdef HAVE_JIKES_NAMESPACE
namespace Jikes { // Open namespace Jikes block
#endif

enum {
      TK_abstract = 35,
      TK_assert = 63,
      TK_boolean = 5,
      TK_break = 64,
      TK_byte = 6,
      TK_case = 95,
      TK_catch = 96,
      TK_char = 7,
      TK_class = 59,
      TK_continue = 65,
      TK_default = 97,
      TK_do = 66,
      TK_double = 8,
      TK_else = 91,
      TK_extends = 98,
      TK_false = 23,
      TK_final = 36,
      TK_finally = 99,
      TK_float = 9,
      TK_for = 67,
      TK_if = 68,
      TK_implements = 102,
      TK_import = 100,
      TK_instanceof = 52,
      TK_int = 10,
      TK_interface = 101,
      TK_long = 11,
      TK_native = 37,
      TK_new = 13,
      TK_null = 24,
      TK_package = 103,
      TK_private = 38,
      TK_protected = 39,
      TK_public = 40,
      TK_return = 69,
      TK_short = 12,
      TK_static = 41,
      TK_strictfp = 42,
      TK_super = 16,
      TK_switch = 70,
      TK_synchronized = 32,
      TK_this = 17,
      TK_throw = 71,
      TK_throws = 104,
      TK_transient = 43,
      TK_true = 25,
      TK_try = 72,
      TK_void = 18,
      TK_volatile = 44,
      TK_while = 61,
      TK_Identifier = 2,
      TK_IntegerLiteral = 26,
      TK_LongLiteral = 27,
      TK_FloatLiteral = 28,
      TK_DoubleLiteral = 29,
      TK_CharacterLiteral = 30,
      TK_StringLiteral = 31,
      TK_PLUS_PLUS = 14,
      TK_MINUS_MINUS = 15,
      TK_EQUAL_EQUAL = 73,
      TK_LESS_EQUAL = 53,
      TK_GREATER_EQUAL = 54,
      TK_NOT_EQUAL = 74,
      TK_LEFT_SHIFT = 45,
      TK_RIGHT_SHIFT = 46,
      TK_UNSIGNED_RIGHT_SHIFT = 47,
      TK_PLUS_EQUAL = 80,
      TK_MINUS_EQUAL = 81,
      TK_MULTIPLY_EQUAL = 82,
      TK_DIVIDE_EQUAL = 83,
      TK_AND_EQUAL = 84,
      TK_OR_EQUAL = 85,
      TK_XOR_EQUAL = 86,
      TK_REMAINDER_EQUAL = 87,
      TK_LEFT_SHIFT_EQUAL = 88,
      TK_RIGHT_SHIFT_EQUAL = 89,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 90,
      TK_OR_OR = 92,
      TK_AND_AND = 75,
      TK_PLUS = 20,
      TK_MINUS = 21,
      TK_NOT = 49,
      TK_REMAINDER = 55,
      TK_XOR = 76,
      TK_AND = 77,
      TK_MULTIPLY = 50,
      TK_OR = 78,
      TK_TWIDDLE = 51,
      TK_DIVIDE = 56,
      TK_GREATER = 57,
      TK_LESS = 58,
      TK_LPAREN = 1,
      TK_RPAREN = 4,
      TK_LBRACE = 34,
      TK_RBRACE = 48,
      TK_LBRACKET = 22,
      TK_RBRACKET = 62,
      TK_SEMICOLON = 3,
      TK_QUESTION = 93,
      TK_COLON = 60,
      TK_COMMA = 33,
      TK_DOT = 19,
      TK_EQUAL = 79,
      TK_BodyMarker = 105,
      TK_enum = 106,
      TK_AT = 107,
      TK_ELLIPSIS = 108,
      TK_const = 109,
      TK_goto = 110,
      TK_ERROR = 111,
      TK_EOF = 94
     };

#ifdef HAVE_JIKES_NAMESPACE
} // Close namespace Jikes block
#endif

#endif /* javasym_INCLUDED */
